services:
  backend:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: docker.arvancloud.ir/postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
